config/routes.rb
Rails.application.routes.draw do
  resources :neuros
  resources :maps
  resources :matches_users
  resources :maps_matches
  resources :matches do
    resources :maps_matches do
      member do
        put "like", to: "maps_matches#upvote"
      end
    end
  end

  devise_for :admins, path: 'admins', controllers: { 
        confirmations: "admins/confirmations",
        mailer: "admins/mailer",
        passwords: "admins/passwords",
        registrations: "admins/registrations",
        sessions: "admins/sessions",
        shared: "admins/shared",
        unlocks: "admins/unlocks"  
  }

  devise_for :users, path: 'users', controllers: { 
    confirmations: "users/confirmations",
    mailer: "users/mailer",
    passwords: "users/passwords",
    registrations: "users/registrations",
    sessions: "users/sessions",
    shared: "users/shared",
    unlocks: "users/unlocks"  
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "matches#index"

end

app/models/map.rb
class Map < ApplicationRecord
    has_many :maps_matches, class_name: 'MapsMatch'         
    has_many :matches, through: :maps_matches, class_name: 'MapsMatch'

    has_attached_file :image, styles: { medium: "300x300>" }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/    
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
    before_action :find_map, only: [:show, :edit, :update, :destroy]
    
        def index
            @maps = Map.all.order("created_at DESC")
        end
    
        def show
    
        end
    
        def new
            @map = Map.new
        end
    
        def create
            @map = Map.new(map_params)
    
            if @map.save
                redirect_to @map, notice: "Map successfully created"
            else
                render 'new'
            end
        end
    
        def edit
        end
    
        def update
            if @map.update(map_params)
                redirect_to @map, notice: "Map successfully updated!"
            else
                render 'edit'
            end
        end
    
        def destroy
            @map.destroy
            redirect_to root_path
        end

        def downvote
            @map.downvote_by current_user
            redirect_to :back
        end


        def upvote
            @map.upvote_by current_user
            redirect_to :back
        end
    
        private
    
        def map_params
            params.require(:map).permit(:image, :title)
        end
    
        def find_map
            @map = Map.find(params[:id])
        end
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/maps/_form.html.haml
= simple_form_for @map, html: {multipart: true} do |f|
    - if @map.errors.any?
        #errors
            %h2
            =pluralize(@map.errors.count, "error")
            prevented this map from saving
            %ul 
                -   @map.errors.full_messages.each do |msg|
                    %li= msg
    .form-group
        = f.input :title, input_html: {class: "form-control"}

    .form-group
        = f.input :image, input_html: {class: "form-control"}
        
    = f.button :submit, class: "btn btn-primary"

app/views/maps/index.html.haml
#maps.transition-enabled
    -   @maps.each do |map|
        .box.panel.panel-default
            =link_to (image_tag map.image.url), map
            .panel-body
                %p= link_to map.title, map
         

    

app/views/maps/new.html.haml
.col-md-6.col-md-offset-3
    %h1 New map  
    =render 'form' 
    =link_to "Back", root_path 

app/views/maps/show.html.haml
#match_show.row
    .col-md-8.col-md-offset-2
        .panel.panel-default
            .panel-heading.pin_image
                %h3= @map.title
                =image_tag @map.image.url(:medium)
                %br/
                %br/
                =link_to "Create another map", new_map_path
                %br/
                =link_to "Back", redirect_to :back
                =link_to "Delete Map", map_path, method: :delete, data: { confirm: "Holy McDoodles, you're deleting this?" } 