config/routes.rb
Rails.application.routes.draw do
  resources :neuros
  resources :maps
  resources :matches_users
  resources :maps_matches
  resources :matches do
    resources :maps_matches do
      member do
        put "like", to: "maps_matches#upvote"
      end
    end
  end

  devise_for :admins, path: 'admins', controllers: { 
        confirmations: "admins/confirmations",
        mailer: "admins/mailer",
        passwords: "admins/passwords",
        registrations: "admins/registrations",
        sessions: "admins/sessions",
        shared: "admins/shared",
        unlocks: "admins/unlocks"  
  }

  devise_for :users, path: 'users', controllers: { 
    confirmations: "users/confirmations",
    mailer: "users/mailer",
    passwords: "users/passwords",
    registrations: "users/registrations",
    sessions: "users/sessions",
    shared: "users/shared",
    unlocks: "users/unlocks"  
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "matches#index"

end

app/models/match.rb
class Match < ApplicationRecord
    acts_as_votable
    
    has_many :matches_users, class_name: 'MatchesUser'
    has_many :maps_matches, class_name: 'MapsMatch'
    has_many :maps, through: :maps_matches, class_name: 'MapsMatch'
    has_many :users, through: :matches_users, class_name: 'MatchesUser'
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

    before_action :find_match, only: [:show, :edit, :update, :destroy]


    def index
        @matches = Match.all.order(:title)
    end

    def show
        
    end

    def new
        @match = Match.new
    end

    def create
        @match = Match.new(match_params)

        if @match.save
            redirect_to @match, notice: "Match successfully created"
        else
            render 'new'
        end

    
    end

    def edit
    end

    def update
        if @match.update(match_params)
            redirect_to @match, notice: "Match successfully updated!"
        else
            render 'edit'
        end
    end

    def destroy
        @match.destroy
        redirect_to root_path
    end


    private

    def match_params
        params.require(:match).permit(:title, :description)
    end

    def find_match
        @match = Match.find(params[:id])
    end

end

app/helpers/matches_helper.rb
module MatchesHelper

end

app/views/matches/_form.html.haml
= simple_form_for @match, html: {multipart: true} do |f|
    - if @match.errors.any?
        #errors
            %h2
            =pluralize(@match.errors.count, "error")
            prevented this match from saving
            %ul 
                -   @match.errors.full_messages.each do |msg|
                    %li= msg
                  
    .form-group
        = f.input :title, input_html: {class: "form-control"}

    .form-group
        = f.input :description, input_html: {class: "form-control"}
    
    = f.button :submit, class: "btn btn-primary"

app/views/matches/edit.html.haml
.col-md-6.col-md-offset-3
    %h1 Edit match

    = render 'form'
        
    = link_to 'Cancel', match_path

app/views/matches/index.html.haml
#match_show.row
    .col-md-8.col-md-offset-2
        #matches.transition-enabled
            -   @matches.each do |match|
                .box.panel.panel-default.matchbox
                    .panel-body
                        %h2= link_to match.title, match
                    

app/views/matches/mymatch.html.haml
#match_show.row
    .col-md-8.col-md-offset-2
        #matches.transition-enabled
            -   @matches.each do |match|
                .box.panel.panel-default.matchbox
                    .panel-body
                        %h2= link_to match.title, match
                    

app/views/matches/new.html.haml
.col-md-6.col-md-offset-3
    %h1 New match  
    =render 'form'
    %br/ 
    =link_to "Back", root_path 

app/views/matches/show.html.haml
#match_show.row
    .col-md-8.col-md-offset-2
        .panel.panel-default
            .panel-heading
                %h1= @match.title 
                %br/
                - @match.matches_users.each do |matches_user|
                    %h4= matches_user.user.team 
            .panel-body
            - if admin_signed_in? || @match.matches_users.select{|u| u.id == current_user.id}.present?  
                #maps.transition-enabled    
                    - @match.maps_matches.each do |maps_match|
                        .box.panel.panel-default
                            =link_to (image_tag maps_match.map.image.url)
                            .panel-body
                                %p= link_to maps_match.map.title
                                = link_to like_match_maps_match_path(maps_match.map), method: :put, class: 'btn btn-default' do
                                    %span.glyphicon.glyphicon-ban-circle
                                    = maps_match.get_likes.size
            - else
                .box.panel.panel-default
                    .panel-body
                        %p You do not have a permission to vote on this match.                                   
            .panel-footer
                .row
                    .col-md-6
                        .btn-group
                            = link_to "Back", root_path
                            - if admin_signed_in?
                                = link_to "Edit", edit_match_path
                                = link_to "Delete", match_path, method: :delete, data: { confirm: "Holy McDoodles, you're deleting this?" }