config/routes.rb
Rails.application.routes.draw do
  resources :neuros
  resources :maps
  resources :matches_users
  resources :maps_matches
  resources :matches do
    resources :maps_matches do
      member do
        put "like", to: "maps_matches#upvote"
      end
    end
  end

  devise_for :admins, path: 'admins', controllers: { 
        confirmations: "admins/confirmations",
        mailer: "admins/mailer",
        passwords: "admins/passwords",
        registrations: "admins/registrations",
        sessions: "admins/sessions",
        shared: "admins/shared",
        unlocks: "admins/unlocks"  
  }

  devise_for :users, path: 'users', controllers: { 
    confirmations: "users/confirmations",
    mailer: "users/mailer",
    passwords: "users/passwords",
    registrations: "users/registrations",
    sessions: "users/sessions",
    shared: "users/shared",
    unlocks: "users/unlocks"  
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "matches#index"

end

app/models/neuro.rb
class Neuro < ApplicationRecord
end

app/controllers/neuros_controller.rb
class NeurosController < ApplicationController
  before_action :set_neuro, only: [:show, :edit, :update, :destroy]

  # GET /neuros
  # GET /neuros.json
  def index
    @neuros = Neuro.all
  end

  # GET /neuros/1
  # GET /neuros/1.json
  def show
  end

  # GET /neuros/new
  def new
    @neuro = Neuro.new
  end

  # GET /neuros/1/edit
  def edit
  end

  # POST /neuros
  # POST /neuros.json
  def create
    @neuro = Neuro.new(neuro_params)

    respond_to do |format|
      if @neuro.save
        format.html { redirect_to @neuro, notice: 'Neuro was successfully created.' }
        format.json { render :show, status: :created, location: @neuro }
      else
        format.html { render :new }
        format.json { render json: @neuro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /neuros/1
  # PATCH/PUT /neuros/1.json
  def update
    respond_to do |format|
      if @neuro.update(neuro_params)
        format.html { redirect_to @neuro, notice: 'Neuro was successfully updated.' }
        format.json { render :show, status: :ok, location: @neuro }
      else
        format.html { render :edit }
        format.json { render json: @neuro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /neuros/1
  # DELETE /neuros/1.json
  def destroy
    @neuro.destroy
    respond_to do |format|
      format.html { redirect_to neuros_url, notice: 'Neuro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_neuro
      @neuro = Neuro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def neuro_params
      params.require(:neuro).permit(:result1, :result2, :playername)
    end
end

app/helpers/neuros_helper.rb
module NeurosHelper
end

app/views/neuros/_form.html.erb
<%= simple_form_for(@neuro) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
      <%= f.input :result1,:label => "First Match Result", input_html: {class: "form-control"} %>
      <%= f.input :result2,:label => "Second Match Result", input_html: {class: "form-control"} %>
      <%= f.input :playername, input_html: {class: "form-control"} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :label => "Analyze"%>
  </div>
<% end %>

app/views/neuros/edit.html.erb
<h1>Editing Neuro</h1>

<%= render 'form', neuro: @neuro %>

<%= link_to 'Show', @neuro %> |
<%= link_to 'Back', neuros_path %>

app/views/neuros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Team Deathmatch Player List</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <div class="row" id="match_show">
      <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-default">
              <tbody>
                <% @neuros.each do |neuro| %>
                <div class="box panel panel-default matchbox">
                    <div class="panel-body">
                      <%= link_to neuro.playername, neuro %>
                    </div>
                </div>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>

<br>

<div class="col-md-8 col-md-offset-2">
    <%= link_to 'New Player Analysis', new_neuro_path %>
</div>

app/views/neuros/new.html.erb
<h1>New Player Analysis</h1>

<%= render 'form', neuro: @neuro %>

<%= link_to 'Back', neuros_path %>

app/views/neuros/show.html.erb
    <p id="notice"><%= notice %></p>
    <% require 'csv' %>
    <% require 'ruby-fann' %> 

    <% x_data = [] %>
    <% y_data = []  %>

    <% CSV.foreach("./data/callofduty-sample-match-scores.csv", :headers => false) do |row|
    x_data.push( [row[0].to_f, row[1].to_f] )
    y_data.push( [row[2].to_i] )
    end %>

    <% test_size_percentange = 20.0 # 20.0% %>
    <% test_set_size = x_data.size * (test_size_percentange/100.to_f) %>

    <% test_x_data = x_data[0 .. (test_set_size-1)] %>
    <% test_y_data = y_data[0 .. (test_set_size-1)] %>

    <% training_x_data = x_data[test_set_size .. x_data.size] %>
    <% training_y_data = y_data[test_set_size .. y_data.size] %>

    <% train = RubyFann::TrainData.new( :inputs=> training_x_data, :desired_outputs=>training_y_data ); %>

    <% model = RubyFann::Standard.new(
                num_inputs: 2,
                hidden_neurons: [6],
                num_outputs: 1 ); %>

    <% model.train_on_data(train, 5000, 500, 0.01) %>
        <div class="box panel panel-default matchbox">
            <div class="panel-body">
    
                <% score1 = @neuro.result1 %>
                <%= "First match score: #{score1}" %> <br/>                

                <% score2 = @neuro.result2 %>
                <%= "Second match score: #{score2}" %> <br/>

                <% prediction = model.run( [score1, score2] )%> 
                <%= "Qualified for playoffs (0 - didn't qualify, 1 - did qualify): #{prediction.map{ |e| e.round }}"%> <br/>

                <% predicted = []
                test_x_data.each do |params|
                predicted.push( model.run(params).map{ |e| e.round } )
                end %>

                <% correct = predicted.collect.with_index { |e,i| (e == test_y_data[i]) ? 1 : 0 }.inject{ |sum,e| sum+e } %>

                <%= "Analysis Accuracy: #{((correct.to_f / test_set_size) * 100).round(2)}% - test set of size #{test_size_percentange}%" %>
            </div>
    </div>    
<%= link_to 'Delete Entry', @neuro, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Edit', edit_neuro_path(@neuro) %> |
<%= link_to 'Back', neuros_path %>