config/routes.rb
Rails.application.routes.draw do
  resources :neuros
  resources :maps
  resources :matches_users
  resources :maps_matches
  resources :matches do
    resources :maps_matches do
      member do
        put "like", to: "maps_matches#upvote"
      end
    end
  end

  devise_for :admins, path: 'admins', controllers: { 
        confirmations: "admins/confirmations",
        mailer: "admins/mailer",
        passwords: "admins/passwords",
        registrations: "admins/registrations",
        sessions: "admins/sessions",
        shared: "admins/shared",
        unlocks: "admins/unlocks"  
  }

  devise_for :users, path: 'users', controllers: { 
    confirmations: "users/confirmations",
    mailer: "users/mailer",
    passwords: "users/passwords",
    registrations: "users/registrations",
    sessions: "users/sessions",
    shared: "users/shared",
    unlocks: "users/unlocks"  
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "matches#index"

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/map.rb
class Map < ApplicationRecord
    has_many :maps_matches, class_name: 'MapsMatch'         
    has_many :matches, through: :maps_matches, class_name: 'MapsMatch'

    has_attached_file :image, styles: { medium: "300x300>" }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/    
end

app/models/maps_match.rb
class MapsMatch < ApplicationRecord
    acts_as_votable

    belongs_to :map
    belongs_to :match
end

app/models/maps_user.rb
class MapsUser < ApplicationRecord
    belongs_to :map
    belongs_to :user
end

app/models/match.rb
class Match < ApplicationRecord
    acts_as_votable
    
    has_many :matches_users, class_name: 'MatchesUser'
    has_many :maps_matches, class_name: 'MapsMatch'
    has_many :maps, through: :maps_matches, class_name: 'MapsMatch'
    has_many :users, through: :matches_users, class_name: 'MatchesUser'
end

app/models/matches_map.rb
class MatchesMap < ApplicationRecord
    belongs_to :map
    belongs_to :match
end

app/models/matches_user.rb
class MatchesUser < ApplicationRecord
    belongs_to :user
    belongs_to :match
end

app/models/neuro.rb
class Neuro < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  acts_as_voter
         
  has_many :matches_users, class_name: 'MatchesUser'         
  has_many :matches, through: :matches_users, class_name: 'MatchesUser'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
    before_action :find_map, only: [:show, :edit, :update, :destroy]
    
        def index
            @maps = Map.all.order("created_at DESC")
        end
    
        def show
    
        end
    
        def new
            @map = Map.new
        end
    
        def create
            @map = Map.new(map_params)
    
            if @map.save
                redirect_to @map, notice: "Map successfully created"
            else
                render 'new'
            end
        end
    
        def edit
        end
    
        def update
            if @map.update(map_params)
                redirect_to @map, notice: "Map successfully updated!"
            else
                render 'edit'
            end
        end
    
        def destroy
            @map.destroy
            redirect_to root_path
        end

        def downvote
            @map.downvote_by current_user
            redirect_to :back
        end


        def upvote
            @map.upvote_by current_user
            redirect_to :back
        end
    
        private
    
        def map_params
            params.require(:map).permit(:image, :title)
        end
    
        def find_map
            @map = Map.find(params[:id])
        end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

    before_action :find_match, only: [:show, :edit, :update, :destroy]


    def index
        @matches = Match.all.order(:title)
    end

    def show
        
    end

    def new
        @match = Match.new
    end

    def create
        @match = Match.new(match_params)

        if @match.save
            redirect_to @match, notice: "Match successfully created"
        else
            render 'new'
        end

    
    end

    def edit
    end

    def update
        if @match.update(match_params)
            redirect_to @match, notice: "Match successfully updated!"
        else
            render 'edit'
        end
    end

    def destroy
        @match.destroy
        redirect_to root_path
    end


    private

    def match_params
        params.require(:match).permit(:title, :description)
    end

    def find_match
        @match = Match.find(params[:id])
    end

end

app/controllers/neuros_controller.rb
class NeurosController < ApplicationController
  before_action :set_neuro, only: [:show, :edit, :update, :destroy]

  # GET /neuros
  # GET /neuros.json
  def index
    @neuros = Neuro.all
  end

  # GET /neuros/1
  # GET /neuros/1.json
  def show
  end

  # GET /neuros/new
  def new
    @neuro = Neuro.new
  end

  # GET /neuros/1/edit
  def edit
  end

  # POST /neuros
  # POST /neuros.json
  def create
    @neuro = Neuro.new(neuro_params)

    respond_to do |format|
      if @neuro.save
        format.html { redirect_to @neuro, notice: 'Neuro was successfully created.' }
        format.json { render :show, status: :created, location: @neuro }
      else
        format.html { render :new }
        format.json { render json: @neuro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /neuros/1
  # PATCH/PUT /neuros/1.json
  def update
    respond_to do |format|
      if @neuro.update(neuro_params)
        format.html { redirect_to @neuro, notice: 'Neuro was successfully updated.' }
        format.json { render :show, status: :ok, location: @neuro }
      else
        format.html { render :edit }
        format.json { render json: @neuro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /neuros/1
  # DELETE /neuros/1.json
  def destroy
    @neuro.destroy
    respond_to do |format|
      format.html { redirect_to neuros_url, notice: 'Neuro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_neuro
      @neuro = Neuro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def neuro_params
      params.require(:neuro).permit(:result1, :result2, :playername)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/maps_matches_helper.rb
module MapsMatchesHelper
end

app/helpers/matches_helper.rb
module MatchesHelper

end

app/helpers/matches_users_helper.rb
module MatchesUsersHelper
end

app/helpers/neuros_helper.rb
module NeurosHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title Vetosys
  = csrf_meta_tags
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-default
      .container
        .navbar-brand= link_to "Vetosys", root_path
        - if admin_signed_in?
          %ul.nav.navbar-nav.navbar-right
            %li= link_to "| Player Analysis |", new_neuro_path
            %li= link_to "| New Match |", new_match_path
            %li= link_to "| New map |", new_map_path
            %li= link_to "| New user relation |", new_matches_user_path
            %li= link_to "| New map relation |", new_maps_match_path
            %li= link_to "| My account |", edit_admin_registration_path
            %li= link_to "| Sign out |", destroy_admin_session_path, method: :delete
        - elsif user_signed_in?
          %ul.nav.navbar-nav.navbar-right
            %li= link_to "My matches"
            %li= link_to "My account", edit_user_registration_path
            %li= link_to "Sign out", destroy_user_session_path, method: :delete
        - else
          %ul.nav.navbar-nav.navbar-right
            %li= link_to "Admin Login", new_admin_session_path
            %li= link_to "Register", new_user_registration_path
            %li= link_to "User Login", new_user_session_path
  .container
    .cover
    .tv
      #tv.screen.mute

  .container 
    - flash.each do |name, msg|
      = content_tag :div, msg, class: "alert alert-info"
    = yield